version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: zeitmanagement
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zeitmanagement
